### ISSUE TITLE
Italian "fork" --guidance needed

### ISSUE THREAD

**Issue by richardmacduff** [LINCnil/GDPR-Developer-Guide#3]
Hello, and thank you.
While waiting for your feedback I proceeded to port sheet 0 through 9 into Italian.
Being not proficient enough at git, and fering messing stuff up (git can be tricky) I opted for the creation of my own separate repository here.
https://github.com/richardmacduff/GDPR-Guida-Sviluppatori

Can you provide me some guidance on how to make a _proper_ fork? I can git but, using it mainly for personal purposes, I never went into the intricacies of a proper multi-actor project.
Thank you very much (in tthe meantime, I'll go on translating the next sheets. BTW, it's an excellent job. Simple, but *dense*. I like how words have been carefully weighed. If one knows what to read, there's plenty of information to bring home.)

Thank you,
W

**Comment by richardmacduff** [comment]
Just to add that all sheets have now been translated.

**Comment by LaboCNIL** [comment]
Hi, many thanks for this work! 

You already made a proper fork on the repository :
https://github.com/richardmacduff/GDPR-Developer-Guide

though this is not the one you've made the translation on. 

From this forked repository, you can either create [a new branch on this repo](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository) or [commit your change](https://help.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits) with your translation.

From this repository, you can also propose a pull request to us, that we would be happy to review!

Best regards
